#!/usr/bin/python

####### imports #########

import os
import cgi
import datetime
import sys
import cgitb
sys.path.append("../Models")
from UserModel import UserModel
from SessionModel import SessionModel

###### imports #########

print """Content-Type: text/html"""

cgitb.enable()

#### Getting the values of the Login Form ######

form = cgi.FieldStorage()#get the form itself

user = form.getvalue("username")#get the value of the input with name 'user'

pasw = form.getvalue("password")#get the value of the input with name 'passwd'

iden = sid = remote = 0

#### End of getting the values of the Login Form ############

#### DataBase Info and connection####### (We must simplify this)

UserModel = UserModel()

SessionModel = SessionModel()

###### End of DataBase Info and Connection #######

###### New Validation ######

valid = UserModel.Get(user, pasw)

if valid:

	iden = UserModel.GetId(user)

	sid = os.getenv("UNIQUE_ID")#get the session id that is going to be a Unique id generated by the system(Unix)

	now = datetime.datetime.now()#generate the TimeStamp

	date = str(now.minute)#converting the TimeStamp to string 	

	remote = os.getenv("REMOTE_ADDR");

	SessionModel.Create(iden, sid, date, remote)

	print("Location:../Views/AdminViews/Dashboard.cgi?uid=%s&sid=%s&remote=%s")%(iden,sid, remote)

else:

	print("Location:../index.cgi?validation=1")

###### New Validation ######

print

del UserModel

del SessionModel

