#!/usr/bin/python

import cgi
import sys 
import os
import cgitb

from datetime import datetime
sys.path.append('../../../bin/')
from FlowQueries import *
from Config import Config
config=Config()
DB_NAME=config.getDBName();
DB_HOST='localhost'
DB_USER=config.getUser();
DB_PASS=config.getPassword();


db = MySQLdb.connect(user=DB_USER, passwd=DB_PASS, db=DB_NAME, host=DB_HOST)
c = db.cursor()

PATH=Config.getFlowsPath()

cgitb.enable()


print "Content-Type: text/html\n\n"

print 

form = cgi.FieldStorage()


def format(results,entity):

        max=results[0][0]

	if max>= 1073741824:
                sizetype="GB"
                typediv=1073741824.0
        elif max >= 1048576:
                sizetype="MB"
                typediv=1048576.0
        elif  max >= 1024:
                sizetype="KB"
                typediv=1024.0
        else:
               sizetype="bytes"
               typediv=1
	
	formatted=""	
	for i in range(len(results)):
                if entity=='net': 
			label = networkmodel.GetLabel(results[i][1])
		elif entity=='ports':
			id=portmodel.GetPortNetwork(results[i][1])[0]
    			labelandport=portmodel.GetGraphInfo( id, results[i][1])
			label="%s-%s"%(labelandport[0],labelandport[1])


		else:
			fromandto=net2netmodel.GetFromandTo(results[i][1])
			From=networkmodel.GetLabel(fromandto[0][0])
			to=networkmodel.GetLabel(fromandto[0][1])
			label="%s to %s"%(From,to)
			
		time=datetime.fromtimestamp(results[i][2]).strftime('%Y-%m-%d %H:%M:%S')
		formatted += "%s,%.2f,%s,%s#100"%(label,results[i][0]/typediv,sizetype,time)


	return formatted#.replace("#!size!#", "%s"%("bytes"));


if form.has_key('id') and form.has_key('type'):

	#int= as | int 
	# type = flows|oct|pak
	
	types={'flows':'1','oct':'2','pak':'3'}

	type=form.getvalue('type')

	id =form.getvalue('id')

	info=GetNetwork(c,id)	
	
	tom=info[3]	

	if tom=='as':
		asn=info[2]

		cmd="/usr/local/flow-tools/bin/flow-cat public_html/webgl/cube/ft-v05.2014-02-04.085500-0400 | /usr/local/flow-tools/bin/flow-filter -a %s | /usr/local/flow-tools/bin/flow-stat -f 9 -S %s | head -n 113"%(asn,types[type])
		pipe=os.popen(cmd)
		top=pipe.read()
		print top

	elif tom=='int':
	
		int=info[1]	
		cmd="/usr/local/flow-tools/bin/flow-cat public_html/webgl/cube/ft-v05.2014-02-04.085500-0400 | /usr/local/flow-tools/bin/flow-filter -i %s | /usr/local/flow-tools/bin/flow-stat -f 9 -S %s | head -n 113"%(asn,types[type])
		pipe=os.popen(cmd)
		top=pipe.read()
		print top
	
	else:
			results="ERROR: Sorry, no Top100 option for Net at the moment\n" 

else:
	results="ERROR: missing params\n"

print results;
