#!/usr/bin/python

import cgi
import sys 
import os
import MySQLdb
import cgitb
from datetime import datetime
sys.path.append('../../../bin/')
from Config import Config
config=Config()
DB_NAME=config.getDBName();
DB_HOST='localhost'
DB_USER=config.getUser();
DB_PASS=config.getPassword();


db = MySQLdb.connect(user=DB_USER, passwd=DB_PASS, db=DB_NAME, host=DB_HOST)
c = db.cursor()
cgitb.enable()

print "Content-Type: text/html\n\n"

print 

form = cgi.FieldStorage()

if form.has_key('entity') and form.has_key('type'):
	
	type=form.getvalue('type')

	entity=form.getvalue('entity')
	
	if entity=='net':
		
		if type=='oct':
			
			sql="select (ooctect+ioctect),label,n_id, time_unix  from rrd_n, NETWORK  where NETWORK.n_id=rrd_n.nid  order  by (ooctect+ioctect) desc limit 100;"
			c.execute(sql)
			results=c.fetchall()

		elif type=='pak':
			
			sql="select (opacks+ipacks),label,n_id, time_unix  from rrd_n, NETWORK  where NETWORK.n_id=rrd_n.nid  order  by (ipacks+opacks) desc limit 100;"
			c.execute(sql)
			results=c.fetchall()
		
		elif type=='flows':
			
			sql="select (oflows+iflows),label,n_id, time_unix  from rrd_n, NETWORK  where NETWORK.n_id=rrd_n.nid  order  by (iflows+oflows) desc limit 100;"
			c.execute(sql)
			results=c.fetchall()
	
		else:
	
			results="ERROR: entity value is not valid\n"

	elif entity=='ports':
		
		if type=='oct':
			
			sql="select (ooctect+ioctect),port,p_id, time_unix  from rrd_port, PORT  where PORT.p_id=rrd_port.pid  order  by (ooctect+ioctect) desc limit 100;"
			c.execute(sql)
			results=c.fetchall()

		elif type=='pak':
			
			sql="select (opacks+ipacks),port,p_id, time_unix  from rrd_port, PORT  where PORT.p_id=rrd_port.pid  order  by (opacks+ipacks) desc limit 100;"
			c.execute(sql)
			results=c.fetchall()
		
		elif type=='flow':
			
			sql="select (oflows+iflows),port,p_id, time_unix  from rrd_port, PORT  where PORT.p_id=rrd_port.pid  order  by (oflows+iflows) desc limit 100;"
			c.execute(sql)
			results=c.fetchall()
	
		else:
	
			results="ERROR: entity value is not valid\n"
	
	elif entity=='p2p':
	
		if type=='oct':
			sql=" select (ooctect+ioctect), time_unix, rrd_to_net.nn_id from rrd_to_net natural join NET2NET order by (ooctect+ioctect) desc limit 100;"	
			c.execute(sql)
			results=c.fetchall()
			#to_label = GetLabelByNumber(c, to_inter, to_inter_type)

		elif type=='pak':
			
			sql=" select (opacks+ipacks), time_unix, rrd_to_net.nn_id from rrd_to_net natural join NET2NET order by (opacks+ipacks) desc limit 100;"	
			c.execute(sql)
			results=c.fetchall()
		
		elif type=='flow':
			
			
			sql="select (oflows+iflows),port,p_id, time_unix  from rrd_port, PORT  where PORT.p_id=rrd_port.pid  order  by (oflows+iflows) desc limit 100;"
			c.execute(sql)
			results=c.fetchall()
	
		else:
	
			results="ERROR: entity value is not valid\n"
	else:

		results="ERROR: entity value not valid\n"


else:
	results="ERROR: missing params\n"

print results;
